### ISSUE TITLE
unable to install yipee on kubernetes

### ISSUE THREAD

**Issue by mohanadj** [yipeeio/yipee#34]
Hi,

I tried to apply the yipee.yaml in my kubernetes server, but it didn't work.

the api container didn't start (CrashLoopBackOff), so i checked the logs of this container and i found this message only:

standard_init_linux.go:207: exec user process caused "no such file or directory"

this is the yaml that i used:
[yipee.txt](https://github.com/yipeeio/yipee/files/2827736/yipee.txt)

please,what should i do?

**Comment by mohanadj** [comment]
Hi,

I tried to apply the yipee.yaml in my kubernetes server, but it didn't work


[yipee.txt](https://github.com/yipeeio/yipee/files/2827718/yipee.txt)

the api container didn't start (CrashLoopBackOff), so i checked the logs of this container and i found this message only:

standard_init_linux.go:207: exec user process caused "no such file or directory"

please,what should i do?

**Comment by mohanadj** [comment]
i tried to change the image tag to (yipeeio/api:2.1) and still not working and the error was image not found.

**Comment by palemtnrider** [comment]
We are aware of the issue with the 2.0 API image.  It was built using dynamic linking instead of static linking.  We should have a new 2.0 API image later today.  I'll update the issue once it is pushed to dockerhub.  Sorry for the inconvenience and thanks for your patience.

**Comment by palemtnrider** [comment]
I've published a new 2.0 and 2.0.1 image that should fix the issue.  You may need to update your yipee.yaml (or editor.yaml) to ensure if pulls the updated image. i.e. change `imagePullPolicy: IfNotPresent` to `imagePullPolicy: Always` for the api image.

**Comment by mohanadj** [comment]
Hi,

I updated the yipee.yaml and it pulled the new image and the api pod is running but it seems it couldn't connect to kubernetes api as you can see in the attached api.log.

[api.log](https://github.com/yipeeio/yipee/files/2832099/api.log)


and the yipee-ui is not starting, it pulls the image but it crashes and keep restarting with the following error:

Logs:
2019/02/05 12:25:48 [emerg] 1#1: host not found in upstream "yipee-backend" in /etc/nginx/conf.d/default.conf:7
nginx: [emerg] host not found in upstream "yipee-backend" in /etc/nginx/conf.d/default.conf:7

========================================

Events:
  Type     Reason                 Age                    From               Message
  ----     ------                 ----                   ----               -------
  Normal   Scheduled              29m                    default-scheduler  Successfully assigned yipee-ui-bf49886dc-hb8wz to minikube
  Normal   SuccessfulMountVolume  29m                    kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-gg68q"
  Normal   Pulled                 28m (x5 over 29m)      kubelet, minikube  Container image "yipeeio/ui:2.0" already present on machine
  Normal   Created                28m (x5 over 29m)      kubelet, minikube  Created container
  Normal   Started                28m (x5 over 29m)      kubelet, minikube  Started container
  Warning  BackOff                4m39s (x109 over 29m)  kubelet, minikube  Back-off restarting failed container
