### ISSUE TITLE
Host path stops yaml generating

### ISSUE THREAD

**Issue by Yomanz** [yipeeio/yipee#35]
If I add a host path to my daemonset it will not generate the yaml.

https://got-your.bigno.se/cfc274e.png
![image](https://user-images.githubusercontent.com/5119107/52970379-7f51c400-33ab-11e9-8c7a-66ddeb38ccd6.png)

https://i-am.bigno.se/427c82c.png
![image](https://user-images.githubusercontent.com/5119107/52970389-84af0e80-33ab-11e9-8164-c7189d35554b.png)

It gets stuck at this:
https://got-your.bigno.se/a397142.png
![image](https://user-images.githubusercontent.com/5119107/52970396-8973c280-33ab-11e9-8f6a-95ecee138749.png)

**Comment by palemtnrider** [comment]
Hi, would you mind uploading those images directly to the github issue?  That will make it easier for us to verify and give us a historical record.  Once you do that we will be able to take a look.

**Comment by Yomanz** [comment]
@palemtnrider Done, sorry for that and the late reply.

**Comment by Yomanz** [comment]
@palemtnrider Hey any thoughts
